### ISSUE TITLE
Provide warnings if recommended extensions are missing on Slots

### ISSUE THREAD

**Issue by jmandel** [inferno-community/fsh-smart-scheduling-links#3]
* BookingDeepLink, BookingPhone -- we should include a warning if these are not populated on a Slot
* BookingCapacity -- we should warn if there's no capacity present (except perhaps for fine-grained slots -- like, if the duration of a slot is <1h, it's probably fine that this is missing)

**Comment by okeefm** [comment]
I also tried to do this in #4. The Capacity only if duration of a slot is >=1h turns out to be hard with the date arithmetic I was able to find in FHIRPath. For the moment I just had it warn for any missing Capacity.
