### ISSUE TITLE
Ensure Schedules are coded for COVID vaccinations

### ISSUE THREAD

**Issue by jmandel** [inferno-community/fsh-smart-scheduling-links#5]
Specifically for the connectathon we're focused on Covid vaccinations. https://fshschool.org/FSHOnline/#/share/3uANN7w (with H/T to Chris and Lloyd from [this thread](https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/Binding.20a.20CodeableConcept.20to.20two.20valuesets) captures the intent.

**Comment by okeefm** [comment]
Makes sense to me. I'll make a PR to merge this into the existing profiles.
